### ISSUE TITLE
Cannot create file - dbpro editor

### ISSUE THREAD

**Issue by dcforeman** [LeeBamberTGC/Dark-Basic-Pro#2]
Downloaded a fresh version from Github, ran the launch.exe application and upon trying to compile any basic dbpro program (such as hello world) I received the following error message:

Cannot create file E:\Github\FPS-Creator-Classic\Dark Basic Pro Shared\Dark Basic Pro\Temp_Temp.dbpro

**Comment by Traductus** [comment]
Hi dcforeman. Could you please answer the following questions to help us find what's causing the issue?
1. What binary did you download Feb 9, or Feb 12?
2. What OS are you currently using?
3. What type of account are you using User or Admin?
4. What permissions does the account have for that folder?

**Comment by TheGameCreators** [comment]
Did you configure the IDE compiler path before pressing F5. You need to point to the DBPCompiler.exe on this screen: 
![image](https://cloud.githubusercontent.com/assets/5113534/13036005/ef8eb6f8-d353-11e5-8cdd-93a5b1264fee.png)

**Comment by dcforeman** [comment]
I posed in the wrong repo! Sorry my bad. This is for FPS Creator which is still using the old IDE.

**Comment by TheGameCreators** [comment]
As Traductus suggests, maybe run in Admin mode, dial UAC to its lowest setting and ensure the folder you are in has full write permissions. When using properties on the folder, you can switch off Read-Only and it will iterate through all the folders and files to set everything to write/execute friendly.
